Update Windows build workflow to support TCP server build configuration

diff --git a/.github/workflows/windows-build.yaml b/.github/workflows/windows-build.yaml
--- a/.github/workflows/windows-build.yaml
+++ b/.github/workflows/windows-build.yaml
@@ -123,7 +123,7 @@ jobs:
         with:
           arch: x64
 
-      - name: Build
+      - name: Build without TCP server support
         working-directory: ${{ runner.temp }}\build
         run: |
           call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
@@ -156,6 +156,41 @@ jobs:
           copy C:\Windows\System32\concrt140.dll . 
           copy C:\Windows\System32\vccorlib140.dll .
           copy C:\Windows\System32\msvcp140.dll .
+
+      - name: Build with TCP Server support
+        working-directory: ${{ runner.temp }}\build
+        run: |
+          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+          
+          echo "Building with qmake..."
+          set PATH=${{ runner.temp }}\\Qt\\${{ env.QT_VERSION }}\\msvc2019_64\\bin;%PATH%
+          qmake -v
+          qmake -r ${{ env.SOURCE_DIR }}\openterfaceQT.pro DEFINES+=HAS_TCPSERVER TARGET=openterfaceQT_TCPServer
+          if errorlevel 1 exit /b 1
+          
+          echo "Building with jom..."
+          ${{ runner.temp }}\jom\jom -j2
+          if errorlevel 1 exit /b 1
+          
+          if not exist release\openterfaceQT.exe (
+            echo "Error: Failed to build openterfaceQT.exe"
+            exit 1
+          )
+          
+          echo "Creating package directory..."
+          mkdir package
+          mkdir package\driver
+          copy release\openterfaceQT.exe package
+          copy ${{ env.SOURCE_DIR }}\LICENSE package
+          copy ${{ env.SOURCE_DIR }}\driver\windows\v3.9\* package\driver
+          
+          echo "Running windeployqt..."
+          cd package
+          windeployqt --qmldir ${{ env.SOURCE_DIR }} openterfaceQT.exe --compiler-runtime --multimedia
+          copy C:\Windows\System32\concrt140.dll . 
+          copy C:\Windows\System32\vccorlib140.dll .
+          copy C:\Windows\System32\msvcp140.dll .
+
 
       - name: Move directory
         working-directory: ${{ runner.temp }}\build
